library(dslabs)
data(murders)
class(murders)
str(murders)
head(murders)
murders$abb
names(murders)
class(murders$state)
z<-3==2
class(z)
?'$'
levels(murders$region)  
class(murders$region)
a<-murders$abb
class(a)
[abb[murders]]
b<-murders[["abb"]]  
class(b)
length(levels(murders$region))
table(region)
?table
a<-(murders$region)
a<-2
b<--1
c<--4
(-b+sqrt(b^2-4*a*c))/(2*a)
(-b-sqrt(b^2-4*a*c))/(2*a)
log(1024,4)
?log
log(1024, base=4)
data(movielens)
str(movielens)
class(movielens$title)
class(movielens$genres)
nlevels(movielens$genres)
b <- murders[["abb"]]
b
murders$abb
table(murders$region)
